### ISSUE TITLE
Not working on portrait mode in android

### ISSUE THREAD

**Issue by Rajesh-Nadar** [FrankSpalteholz/UnityMediapipeIris#1]
I am using Unity 2020.3.1f1 Android

I built the example scene and the face detection only working properly when I keep my phone in landscape mode on portrait mode the faceDetect view just rotates left to right

**Comment by yugosaito4** [comment]
@Rajesh-Nadar  had the same problem here. You have to rotate the input since it expects a landscape face . Another solution is to rotate the output

**Comment by Rajesh-Nadar** [comment]
@yugosaito4  Yeah I understood the problem but I don't know how I can rotate the image or where should I write the rotation function/ shader.
